## 14.1 Filtering on string

In [1]:
import pandas as pd

data = {
    "Name": ["Alice", "Bob", "Charlie", "David", "Eve", "Frank", "Grace", "Hannah","Saku"],
    "City": ["New York", "Los Angeles", "Newark", "Boston", "New Delhi", "Chicago", "New Orleans", "Houston","A Los Carol"],
    "Department": ["HR", "IT", "Finance", "IT", "HR", "Marketing", "Finance", "HR", "HR"],
    "Salary": [50000, 60000, 55000, 70000, 52000, 58000, 62000, 51000,1245]
}

df = pd.DataFrame(data)

In [2]:
df

      Name         City Department  Salary
0    Alice     New York         HR   50000
1      Bob  Los Angeles         IT   60000
2  Charlie       Newark    Finance   55000
3    David       Boston         IT   70000
4      Eve    New Delhi         HR   52000
5    Frank      Chicago  Marketing   58000
6    Grace  New Orleans    Finance   62000
7   Hannah      Houston         HR   51000
8     Saku  A Los Carol         HR    1245

In [3]:
df.loc[df['City'].str.contains("New")]

      Name         City Department  Salary
0    Alice     New York         HR   50000
2  Charlie       Newark    Finance   55000
4      Eve    New Delhi         HR   52000
6    Grace  New Orleans    Finance   62000

In [4]:
# To false down the case sensativeness
df.loc[df['City'].str.contains("new",case = False)]

      Name         City Department  Salary
0    Alice     New York         HR   50000
2  Charlie       Newark    Finance   55000
4      Eve    New Delhi         HR   52000
6    Grace  New Orleans    Finance   62000

In [5]:
# Start with los [print all Los]
df.loc[df['City'].str.contains(r"Los")]

   Name         City Department  Salary
1   Bob  Los Angeles         IT   60000
8  Saku  A Los Carol         HR    1245

In [6]:
# Print just start with Los
df.loc[df['City'].str.contains(r"^Los")]

  Name         City Department  Salary
1  Bob  Los Angeles         IT   60000

In [7]:
# Ending with rk
df.loc[df['City'].str.contains(r"rk$")]

      Name      City Department  Salary
0    Alice  New York         HR   50000
2  Charlie    Newark    Finance   55000

In [8]:
# Start with Vowel
df.loc[df['Name'].str.contains(r"^[AEIOU]")]

    Name       City Department  Salary
0  Alice   New York         HR   50000
4    Eve  New Delhi         HR   52000

In [9]:
# Include New or Los
df.loc[df['City'].str.contains(r"New|Los")]

      Name         City Department  Salary
0    Alice     New York         HR   50000
1      Bob  Los Angeles         IT   60000
2  Charlie       Newark    Finance   55000
4      Eve    New Delhi         HR   52000
6    Grace  New Orleans    Finance   62000
8     Saku  A Los Carol         HR    1245

## 14.2 Adding new Column and Saving the File

In [10]:
df1 = pd.read_csv('student_data.csv')

In [11]:
# adding a constant column
df['Country'] = 'Bangladesh'
df

      Name         City Department  Salary     Country
0    Alice     New York         HR   50000  Bangladesh
1      Bob  Los Angeles         IT   60000  Bangladesh
2  Charlie       Newark    Finance   55000  Bangladesh
3    David       Boston         IT   70000  Bangladesh
4      Eve    New Delhi         HR   52000  Bangladesh
5    Frank      Chicago  Marketing   58000  Bangladesh
6    Grace  New Orleans    Finance   62000  Bangladesh
7   Hannah      Houston         HR   51000  Bangladesh
8     Saku  A Los Carol         HR    1245  Bangladesh

In [12]:
# Total Marks
df1['Total Marks'] = df1['Data Structure Marks'] + df1['Algorithm Marks'] + df1['Python Marks']
df1

,StudentID,FullName,Data Structure Marks,Algorithm Marks,Python Marks,CompletionStatus,EnrollmentDate,Instructor,Location,Total Marks
0,PH1001,Alif Rahman,85.0,85.0,88.0,Completed,2024-01-15,Mr. Karim,Dhaka,258.0
1,PH1002,Fatima Akhter,92.0,92.0,NaN,In Progress,2024-01-20,Ms. Salma,Chattogram,NaN
2,PH1003,Imran Hossain,88.0,88.0,85.0,Completed,2024-02-10,Mr. Karim,Dhaka,261.0
3,PH1004,Jannatul Ferdous,78.0,78.0,82.0,Completed,2024-02-12,Ms. Salma,Sylhet,238.0
4,PH1005,Kamal Uddin,NaN,NaN,95.0,In Progress,2024-03-05,Mr. Karim,Chattogram,NaN
5,PH1006,Laila Begum,75.0,75.0,78.0,Completed,2024-03-08,Ms. Salma,Rajshahi,228.0
6,PH1007,Mahmudul Hasan,80.0,80.0,NaN,In Progress,2024-04-01,Mr. Karim,Dhaka,NaN
7,PH1008,Nadia Islam,81.0,81.0,85.0,Completed,2024-04-22,Ms. Salma,Chattogram,247.0
8,PH1009,Omar Faruq,72.0,72.0,76.0,Completed,2024-05-16,Mr. David,Dhaka,220.0
9,PH1010,Priya Sharma,89.0,89.0,88.0,Completed,2024-05-20,Ms. Salma,Sylhet,266.0
10,PH1011,Rahim Sheikh,NaN,NaN,91.0,In Progress,2024-06-11,Mr. Karim,Khulna,NaN
11,PH1012,Sadia Chowdhury,85.0,85.0,87.0,Completed,2024-06-14,Ms. Salma,Chattogram,257.0
12,PH1013,Tanvir Ahmed,75.0,75.0,79.0,Completed,2024-07-02,Mr. David,Dhaka,229.0
13,PH1014,Urmi Akter,NaN,NaN,NaN,Not Started,2024-07-09,Ms. Salma,Rajshahi,NaN
14,PH1015,Wahiduzzaman,86.0,86.0,84.0,Completed,2024-08-18,Mr. Karim,Dhaka,256.0
15,PH1016,Ziaur Rahman,94.0,94.0,NaN,In Progress,2024-08-21,Ms. Salma,Chattogram,NaN
16,PH1017,Afsana Mimi,90.0,90.0,93.0,Completed,2025-09-01,Mr. Karim,Dhaka,273.0
17,PH1018,Babul Ahmed,88.0,88.0,85.0,Completed,2025-09-05,Ms. Salma,Sylhet,261.0
18,PH1019,Faria Rahman,NaN,NaN,NaN,Not Started,2025-09-15,Mr. David,Chattogram,NaN
19,PH1020,Nasir Khan,86.0,86.0,89.0,Completed,2025-10-02,Ms. Salma,Dhaka,261.0

In [13]:
import numpy as np
df['A+ i DS'] = np.where(df['Data Structure Marks']>90, 'A+','A')
df

KeyError: 'Data Structure Marks'

In [ ]:
df['Passed in DS'] = df['Data Structure Marks']>70
df

In [ ]:
# Making first name column
df['First Name'] = df['FullName'].str.split(' ').str[0]
df

In [ ]:
# Save
df.to_csv('New_Student_data.csv')
df

## 14.3 Checking Duplicates and Null Values in DF

In [ ]:
data = {
    "Name": ["Alice", "Bob", "Charlie", "Alice", "David", "Bob"],
    "City": ["New York", "London", "Paris", "New York", "Tokyo", "London"],
    "Score": [85, 90, 78, 85, 95, 90]
}

df = pd.DataFrame(data)
print(df)

In [ ]:
# Check Null
df['Name'].unique()
len(df['Name'].unique())

In [ ]:
# Unique with Null
len(df1['Data Structure Marks'].unique())
# Unique with Null
df1['Data Structure Marks'].nunique()

# *** Unique Works only on series ***

In [ ]:
df1.nunique()

In [ ]:
df1.isnull()

In [ ]:
df1['Data Structure Marks'].notnull()

In [ ]:
df1['Data Structure Marks'].hasnans

In [ ]:
df1['StudentID'].hasnans

## 14.4 Handling Duplicates Values

In [ ]:
import pandas as pd

data = {
    "Name": ["Alice", "Bob", "Charlie", "David", "Eve", "Frank", "Grace", "Hannah","Hannah"],
    "City": ["New York", "Los Angeles", "Newark", "Boston", "New Delhi", "Chicago", "New Orleans", "Houston","Houston"],
    "Department": ["HR", "IT", "Finance", "IT", "HR", "Marketing", "Finance", "HR", "HR"],
    "Salary": [50000, 60000, 55000, 70000, 52000, 58000, 62000, 51000,51000]
}

df = pd.DataFrame(data)

In [ ]:
df.duplicated().sum()

In [ ]:
# Deleting dublicate value
df.drop_duplicates()

In [ ]:
# Parmanently Deleting dublicate value
df.drop_duplicates(inplace = True)

In [ ]:
df.duplicated().sum()

In [ ]:
# Basis of any column Delete Duplcaion
# Parmanently Deleting dublicate value
df.drop_duplicates(subset=['Department'])

In [ ]:
df.drop_duplicates(subset=['Department'],keep='last')

## 14.5 Handling Null Values

In [ ]:
df.dropna()

In [ ]:
df1.dropna(how='all')

In [ ]:
df1.dropna(subset=['Python Marks','Algorithm Marks'])

In [ ]:
df1.fillna(0)

In [ ]:
df1['FullName'].fillna('Unknown')

In [ ]:
df1

In [ ]:
df1['Python Marks'] = df1['Python Marks'].fillna(df1['Python Marks'].mean())

In [ ]:
df1

In [ ]:
df1['Data Structure Marks'].sum()

In [ ]:
df1['Data Structure Marks'].min()

In [ ]:
df1['Data Structure Marks'].max()

In [ ]:
print(df1['Data Structure Marks'].mean())

In [ ]:
print(df1['Data Structure Marks'].median())

In [ ]:
df1['Data Structure Marks'].mode()

In [ ]:
df1['Data Structure Marks'].std()

In [ ]:
print(df1['Data Structure Marks'].sum())

In [ ]:
df1[['Data Structure Marks','Python Marks']].corr()

In [ ]:
# Sum in different column
df1[['Data Structure Marks','Python Marks']].sum()

In [ ]:
# Sum in different column row wise
df1[['Data Structure Marks','Python Marks']].sum(axis=1)

In [ ]:
df1['Total Marks'] = df1.iloc[::,2:5].sum(axis=1)

In [ ]:
df1

In [ ]:
df1.describe()

# Apply Function in DF

In [ ]:
mn = df1['Total Marks'].min()
mx = df1['Total Marks'].max()
df1['Scaled Marks'] = df1['Total Marks'].apply(lambda x: (x-mn)/(mx-mn))

In [ ]:
df1

In [ ]:
# Custom made Function

def grading_system(marks):
    if marks >= 260:
        return 'A+'
    elif marks >= 250:
        return 'A'
    else:
        return 'A-'

df1['Grade'] = df1['Total Marks'].apply(grading_system)

In [ ]:
df1

In [ ]:
def Marking_System(df1):
    a = df1['Data Structure Marks'] * 3
    b = df1['Algorithm Marks'] * 2
    c = df1['Python Marks'] * 5
    return a+b+c


df1['Exceptional Marks'] = df1.apply(Marking_System,axis=1)

In [14]:
df1

,StudentID,FullName,Data Structure Marks,Algorithm Marks,Python Marks,CompletionStatus,EnrollmentDate,Instructor,Location,Total Marks
0,PH1001,Alif Rahman,85.0,85.0,88.0,Completed,2024-01-15,Mr. Karim,Dhaka,258.0
1,PH1002,Fatima Akhter,92.0,92.0,NaN,In Progress,2024-01-20,Ms. Salma,Chattogram,NaN
2,PH1003,Imran Hossain,88.0,88.0,85.0,Completed,2024-02-10,Mr. Karim,Dhaka,261.0
3,PH1004,Jannatul Ferdous,78.0,78.0,82.0,Completed,2024-02-12,Ms. Salma,Sylhet,238.0
4,PH1005,Kamal Uddin,NaN,NaN,95.0,In Progress,2024-03-05,Mr. Karim,Chattogram,NaN
5,PH1006,Laila Begum,75.0,75.0,78.0,Completed,2024-03-08,Ms. Salma,Rajshahi,228.0
6,PH1007,Mahmudul Hasan,80.0,80.0,NaN,In Progress,2024-04-01,Mr. Karim,Dhaka,NaN
7,PH1008,Nadia Islam,81.0,81.0,85.0,Completed,2024-04-22,Ms. Salma,Chattogram,247.0
8,PH1009,Omar Faruq,72.0,72.0,76.0,Completed,2024-05-16,Mr. David,Dhaka,220.0
9,PH1010,Priya Sharma,89.0,89.0,88.0,Completed,2024-05-20,Ms. Salma,Sylhet,266.0
10,PH1011,Rahim Sheikh,NaN,NaN,91.0,In Progress,2024-06-11,Mr. Karim,Khulna,NaN
11,PH1012,Sadia Chowdhury,85.0,85.0,87.0,Completed,2024-06-14,Ms. Salma,Chattogram,257.0
12,PH1013,Tanvir Ahmed,75.0,75.0,79.0,Completed,2024-07-02,Mr. David,Dhaka,229.0
13,PH1014,Urmi Akter,NaN,NaN,NaN,Not Started,2024-07-09,Ms. Salma,Rajshahi,NaN
14,PH1015,Wahiduzzaman,86.0,86.0,84.0,Completed,2024-08-18,Mr. Karim,Dhaka,256.0
15,PH1016,Ziaur Rahman,94.0,94.0,NaN,In Progress,2024-08-21,Ms. Salma,Chattogram,NaN
16,PH1017,Afsana Mimi,90.0,90.0,93.0,Completed,2025-09-01,Mr. Karim,Dhaka,273.0
17,PH1018,Babul Ahmed,88.0,88.0,85.0,Completed,2025-09-05,Ms. Salma,Sylhet,261.0
18,PH1019,Faria Rahman,NaN,NaN,NaN,Not Started,2025-09-15,Mr. David,Chattogram,NaN
19,PH1020,Nasir Khan,86.0,86.0,89.0,Completed,2025-10-02,Ms. Salma,Dhaka,261.0

# DateTime and Time Delta

In [15]:
df1['EnrollmentDate'] = pd.to_datetime(df1['EnrollmentDate'])

In [16]:
df1['EnrollmentDate']

0    2024-01-15
1    2024-01-20
2    2024-02-10
3    2024-02-12
4    2024-03-05
5    2024-03-08
6    2024-04-01
7    2024-04-22
8    2024-05-16
9    2024-05-20
10   2024-06-11
11   2024-06-14
12   2024-07-02
13   2024-07-09
14   2024-08-18
15   2024-08-21
16   2025-09-01
17   2025-09-05
18   2025-09-15
19   2025-10-02
Name: EnrollmentDate, dtype: datetime64[ns]

In [17]:
df1['EnrollmentDate'] = df1['EnrollmentDate'].dt.year

In [18]:
df1['EnrollmentDate']

0     2024
1     2024
2     2024
3     2024
4     2024
5     2024
6     2024
7     2024
8     2024
9     2024
10    2024
11    2024
12    2024
13    2024
14    2024
15    2024
16    2025
17    2025
18    2025
19    2025
Name: EnrollmentDate, dtype: int32

In [19]:
df1

,StudentID,FullName,Data Structure Marks,Algorithm Marks,Python Marks,CompletionStatus,EnrollmentDate,Instructor,Location,Total Marks
0,PH1001,Alif Rahman,85.0,85.0,88.0,Completed,2024,Mr. Karim,Dhaka,258.0
1,PH1002,Fatima Akhter,92.0,92.0,NaN,In Progress,2024,Ms. Salma,Chattogram,NaN
2,PH1003,Imran Hossain,88.0,88.0,85.0,Completed,2024,Mr. Karim,Dhaka,261.0
3,PH1004,Jannatul Ferdous,78.0,78.0,82.0,Completed,2024,Ms. Salma,Sylhet,238.0
4,PH1005,Kamal Uddin,NaN,NaN,95.0,In Progress,2024,Mr. Karim,Chattogram,NaN
5,PH1006,Laila Begum,75.0,75.0,78.0,Completed,2024,Ms. Salma,Rajshahi,228.0
6,PH1007,Mahmudul Hasan,80.0,80.0,NaN,In Progress,2024,Mr. Karim,Dhaka,NaN
7,PH1008,Nadia Islam,81.0,81.0,85.0,Completed,2024,Ms. Salma,Chattogram,247.0
8,PH1009,Omar Faruq,72.0,72.0,76.0,Completed,2024,Mr. David,Dhaka,220.0
9,PH1010,Priya Sharma,89.0,89.0,88.0,Completed,2024,Ms. Salma,Sylhet,266.0
10,PH1011,Rahim Sheikh,NaN,NaN,91.0,In Progress,2024,Mr. Karim,Khulna,NaN
11,PH1012,Sadia Chowdhury,85.0,85.0,87.0,Completed,2024,Ms. Salma,Chattogram,257.0
12,PH1013,Tanvir Ahmed,75.0,75.0,79.0,Completed,2024,Mr. David,Dhaka,229.0
13,PH1014,Urmi Akter,NaN,NaN,NaN,Not Started,2024,Ms. Salma,Rajshahi,NaN
14,PH1015,Wahiduzzaman,86.0,86.0,84.0,Completed,2024,Mr. Karim,Dhaka,256.0
15,PH1016,Ziaur Rahman,94.0,94.0,NaN,In Progress,2024,Ms. Salma,Chattogram,NaN
16,PH1017,Afsana Mimi,90.0,90.0,93.0,Completed,2025,Mr. Karim,Dhaka,273.0
17,PH1018,Babul Ahmed,88.0,88.0,85.0,Completed,2025,Ms. Salma,Sylhet,261.0
18,PH1019,Faria Rahman,NaN,NaN,NaN,Not Started,2025,Mr. David,Chattogram,NaN
19,PH1020,Nasir Khan,86.0,86.0,89.0,Completed,2025,Ms. Salma,Dhaka,261.0

In [26]:
df1 = pd.read_csv('student_data.csv')

In [27]:
df1['EnrollmentDate'] = pd.to_datetime(df1['EnrollmentDate'])

In [28]:
df1['Enrollment Date'] = df1['EnrollmentDate'].dt.day

In [29]:
df1

,StudentID,FullName,Data Structure Marks,Algorithm Marks,Python Marks,CompletionStatus,EnrollmentDate,Instructor,Location,Enrollment Date
0,PH1001,Alif Rahman,85.0,85.0,88.0,Completed,2024-01-15,Mr. Karim,Dhaka,15
1,PH1002,Fatima Akhter,92.0,92.0,NaN,In Progress,2024-01-20,Ms. Salma,Chattogram,20
2,PH1003,Imran Hossain,88.0,88.0,85.0,Completed,2024-02-10,Mr. Karim,Dhaka,10
3,PH1004,Jannatul Ferdous,78.0,78.0,82.0,Completed,2024-02-12,Ms. Salma,Sylhet,12
4,PH1005,Kamal Uddin,NaN,NaN,95.0,In Progress,2024-03-05,Mr. Karim,Chattogram,5
5,PH1006,Laila Begum,75.0,75.0,78.0,Completed,2024-03-08,Ms. Salma,Rajshahi,8
6,PH1007,Mahmudul Hasan,80.0,80.0,NaN,In Progress,2024-04-01,Mr. Karim,Dhaka,1
7,PH1008,Nadia Islam,81.0,81.0,85.0,Completed,2024-04-22,Ms. Salma,Chattogram,22
8,PH1009,Omar Faruq,72.0,72.0,76.0,Completed,2024-05-16,Mr. David,Dhaka,16
9,PH1010,Priya Sharma,89.0,89.0,88.0,Completed,2024-05-20,Ms. Salma,Sylhet,20
10,PH1011,Rahim Sheikh,NaN,NaN,91.0,In Progress,2024-06-11,Mr. Karim,Khulna,11
11,PH1012,Sadia Chowdhury,85.0,85.0,87.0,Completed,2024-06-14,Ms. Salma,Chattogram,14
12,PH1013,Tanvir Ahmed,75.0,75.0,79.0,Completed,2024-07-02,Mr. David,Dhaka,2
13,PH1014,Urmi Akter,NaN,NaN,NaN,Not Started,2024-07-09,Ms. Salma,Rajshahi,9
14,PH1015,Wahiduzzaman,86.0,86.0,84.0,Completed,2024-08-18,Mr. Karim,Dhaka,18
15,PH1016,Ziaur Rahman,94.0,94.0,NaN,In Progress,2024-08-21,Ms. Salma,Chattogram,21
16,PH1017,Afsana Mimi,90.0,90.0,93.0,Completed,2025-09-01,Mr. Karim,Dhaka,1
17,PH1018,Babul Ahmed,88.0,88.0,85.0,Completed,2025-09-05,Ms. Salma,Sylhet,5
18,PH1019,Faria Rahman,NaN,NaN,NaN,Not Started,2025-09-15,Mr. David,Chattogram,15
19,PH1020,Nasir Khan,86.0,86.0,89.0,Completed,2025-10-02,Ms. Salma,Dhaka,2

In [ ]:
df1['EnrollmentDate'] = pd.to_datetime(df1['EnrollmentDate'])

# Group By

In [32]:
group = df1.groupby('Instructor')

In [33]:
group

In [34]:
df1 = pd.read_csv('student_data.csv')

In [35]:
group = df1.groupby('Instructor')

In [36]:
group.sum()

,StudentID,FullName,Data Structure Marks,Algorithm Marks,Python Marks,CompletionStatus,EnrollmentDate,Location
Instructor,,,,,,,,
Mr. David,PH1009PH1013PH1019,Omar FaruqTanvir AhmedFaria Rahman,147.0,147.0,155.0,CompletedCompletedNot Started,2024-05-162024-07-022025-09-15,DhakaDhakaChattogram
Mr. Karim,PH1001PH1003PH1005PH1007PH1011PH1015PH1017,Alif RahmanImran HossainKamal UddinMahmudul Ha...,429.0,429.0,536.0,CompletedCompletedIn ProgressIn ProgressIn Pro...,2024-01-152024-02-102024-03-052024-04-012024-0...,DhakaDhakaChattogramDhakaKhulnaDhakaDhaka
Ms. Salma,PH1002PH1004PH1006PH1008PH1010PH1012PH1014PH10...,Fatima AkhterJannatul FerdousLaila BegumNadia ...,768.0,768.0,594.0,In ProgressCompletedCompletedCompletedComplete...,2024-01-202024-02-122024-03-082024-04-222024-0...,ChattogramSylhetRajshahiChattogramSylhetChatto...

In [37]:
group.min()

,StudentID,FullName,Data Structure Marks,Algorithm Marks,Python Marks,CompletionStatus,EnrollmentDate,Location
Instructor,,,,,,,,
Mr. David,PH1009,Faria Rahman,72.0,72.0,76.0,Completed,2024-05-16,Chattogram
Mr. Karim,PH1001,Afsana Mimi,80.0,80.0,84.0,Completed,2024-01-15,Chattogram
Ms. Salma,PH1002,Babul Ahmed,75.0,75.0,78.0,Completed,2024-01-20,Chattogram

In [38]:
group.max()

,StudentID,FullName,Data Structure Marks,Algorithm Marks,Python Marks,CompletionStatus,EnrollmentDate,Location
Instructor,,,,,,,,
Mr. David,PH1019,Tanvir Ahmed,75.0,75.0,79.0,Not Started,2025-09-15,Dhaka
Mr. Karim,PH1017,Wahiduzzaman,90.0,90.0,95.0,In Progress,2025-09-01,Khulna
Ms. Salma,PH1020,Ziaur Rahman,94.0,94.0,89.0,Not Started,2025-10-02,Sylhet

In [39]:
group.first()

,StudentID,FullName,Data Structure Marks,Algorithm Marks,Python Marks,CompletionStatus,EnrollmentDate,Location
Instructor,,,,,,,,
Mr. David,PH1009,Omar Faruq,72.0,72.0,76.0,Completed,2024-05-16,Dhaka
Mr. Karim,PH1001,Alif Rahman,85.0,85.0,88.0,Completed,2024-01-15,Dhaka
Ms. Salma,PH1002,Fatima Akhter,92.0,92.0,82.0,In Progress,2024-01-20,Chattogram

In [40]:
group.last()

,StudentID,FullName,Data Structure Marks,Algorithm Marks,Python Marks,CompletionStatus,EnrollmentDate,Location
Instructor,,,,,,,,
Mr. David,PH1019,Faria Rahman,75.0,75.0,79.0,Not Started,2025-09-15,Chattogram
Mr. Karim,PH1017,Afsana Mimi,90.0,90.0,93.0,Completed,2025-09-01,Dhaka
Ms. Salma,PH1020,Nasir Khan,86.0,86.0,89.0,Completed,2025-10-02,Dhaka

In [41]:
import pandas as pd

def delete_duplicate_emails(person: pd.DataFrame) -> None:
    person.sort_values('id',inplace=True)
    person.drop_duplicates('email',inplace=True)

# Problem Solving 2

In [ ]:
import pandas as pd

def count_salary_categories(accounts: pd.DataFrame) -> pd.DataFrame:
    low_salary = (accounts['income']<20000).sum()
    average_salary = ((accounts['income']>=20000) & (accounts['income']<=50000)).sum()
    high_salary = (accounts['income']>50000).sum()

    data = [('Low Salary', low_salary),('Average Salary', average_salary),('High Salary', high_salary)]

    df = pd.DataFrame(data, columns = ['category','accounts_count'])
    return df

In [48]:
data = {
"Name": ["Alice", "Bob", "Charlie"],
"Age": [25, 30, 35],
"City": ["New York", "London", "Paris"]
}
df = pd.DataFrame(data)
df.shape

(3, 3)